baseURL = 'https://www.tejbirwason.com'
languageCode = 'en-us'
title = 'Tejbir (Tj) Wason'
theme = "cactus"
[params]
description = "Brief musings and general learnings"
mainSectionTitle = "TIL's"
showAllPostsOnHomePage = true
[[params.social]]
name = "github"
link = "https://github.com/tejbirwason"

[[params.social]]
name = "email"
link = "tejbirwason@gmail.com" # no need for "mailto:" at the start

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/tejbirwason/"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
